/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuizEconomizarHorasEmFilasRouteImport } from './routes/quiz-economizar-horas-em-filas'
import { Route as IndexRouteImport } from './routes/index'

const QuizEconomizarHorasEmFilasRoute =
  QuizEconomizarHorasEmFilasRouteImport.update({
    id: '/quiz-economizar-horas-em-filas',
    path: '/quiz-economizar-horas-em-filas',
    getParentRoute: () => rootRouteImport,
  } as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/quiz-economizar-horas-em-filas': typeof QuizEconomizarHorasEmFilasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/quiz-economizar-horas-em-filas': typeof QuizEconomizarHorasEmFilasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/quiz-economizar-horas-em-filas': typeof QuizEconomizarHorasEmFilasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/quiz-economizar-horas-em-filas'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/quiz-economizar-horas-em-filas'
  id: '__root__' | '/' | '/quiz-economizar-horas-em-filas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  QuizEconomizarHorasEmFilasRoute: typeof QuizEconomizarHorasEmFilasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quiz-economizar-horas-em-filas': {
      id: '/quiz-economizar-horas-em-filas'
      path: '/quiz-economizar-horas-em-filas'
      fullPath: '/quiz-economizar-horas-em-filas'
      preLoaderRoute: typeof QuizEconomizarHorasEmFilasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  QuizEconomizarHorasEmFilasRoute: QuizEconomizarHorasEmFilasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
